#!/usr/bin/perl -w

use CHAP;

use UniLang::Agent::Agent;
use UniLang::Util::Message;

$UNIVERSAL::agent = UniLang::Agent::Agent->new
  (Name => "CHAP",
   ReceiveHandler => \&Receive);
$UNIVERSAL::chap = CHAP->new();

sub Receive {
  my %args = @_;
  $UNIVERSAL::chap->ProcessMessage
    (Message => $args{Message});
}

$UNIVERSAL::chap->Execute();
